name: Build binaries
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15-intel, macos-15, windows-2025, windows-11-arm]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'true'
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install pyinstaller and dependencies
        run: pip3 install --upgrade pyinstaller requests

      - name: Build C module
        run: pip3 install -e . 

      - name: Set strip on Linux and Mac
        id: strip
        run: echo "option=--strip" >> $GITHUB_OUTPUT
        if: runner.os != 'Windows'

      - name: Build
        run: pyinstaller
          --onefile
          --name gogdl
          ${{ steps.strip.outputs.option }}
          gogdl/cli.py
        env:
          PYTHONOPTIMIZE: 1

      - uses: actions/upload-artifact@v6
        with:
          name: gogdl-${{ matrix.os }}
          path: dist/*

  draft:
    needs: build
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/download-artifact@v7
      - run: mkdir -p release
      - run: |
          mv gogdl-ubuntu-24.04/gogdl release/gogdl_linux_x86_64
          mv gogdl-ubuntu-24.04-arm/gogdl release/gogdl_linux_arm64
          mv gogdl-macos-15-intel/gogdl release/gogdl_macos_x86_64
          mv gogdl-macos-15/gogdl release/gogdl_macos_arm64
          mv gogdl-windows-2025/gogdl.exe release/gogdl_windows_x86_64.exe 
          mv gogdl-windows-11-arm/gogdl.exe release/gogdl_windows_arm64.exe 

      - uses: softprops/action-gh-release@v2
        with: 
          files: release/gogdl*
